### ISSUE TITLE
Latest dev build and some previous builds I noticed there are instances where op's can't break a players door

### ISSUE THREAD

**Issue by axemwa** [TownyAdvanced/Towny#3073]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. On occassion attempting to destory a door as a op doesn't work and townys "you are not allowed to do this etc" message appeared
2.
3.

### What is the expected output?
1. Op's should be able to break anything
2.
3.

### What is your Towny version?
Version: 0.93.0.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-366 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/8LpV84xB
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/N9Cec69h
3. Your townyperms.yml : https://pastebin.com/BkNV74bH
4. Your log's error : In-game says something like this, "Outsiders are not allowed to destroy here".
5. There are times when Op can destroy again, the op not being able to destroy seems to randomly happen so I can't always reproduce the issue

(optional) If this is to do with permissions, 
5. Your permissions file : n/a

(optional) If this is to do with chat,
6. Your chatconfig.yml : n/a
7. Your channels.yml :n/a

**Comment by LlmDl** [comment]
If you'd like to test this on a build made for 1.13 I am pretty sure this is already fixed:
https://cdn.discordapp.com/attachments/487025202539266048/500317161177219075/Towny.jar

Let me know if it works.

**Comment by axemwa** [comment]
ok will do thanx

**Comment by axemwa** [comment]
i noticed there's even newer versions in the file repo should I get that one instead if so the bottom one on second to last one at the bottom? http://towny.palmergames.com/file-repo/Towny%20Advanced/Development/

**Comment by LlmDl** [comment]
No that was a typo, what I already linked is the one to use.

**Comment by axemwa** [comment]
It still happens in this version you sent me too but... only difference now is that it won't let me place the door... AHA! think I know why it happens on occasion now, it seems like when a player is given op when they are already in the game the op permissions don't work for the doors atleast, but when a player is given op permission ingame and they log out/eave then back in/join the op permissions do work (well only if deop-everyone-on-join: is set to true in worlguard that is, otherwise the op permission doesn't work at all for doors in a player town region). Here's a vid of the issue happening when op is given ingame before they leave the server.

https://youtu.be/QVUnQ9A8G0A

**Comment by LlmDl** [comment]
I want to say this might be slightly affected by LuckPerm's caching system? You could try it out without LP installed and figure out right away if it's the culprit.

**Comment by LlmDl** [comment]
Also, in your video: There's no Towny denial message. It could only show once or twice for the chunk you're in, afterwards the message is silent. You can try it out again by leaving the chunk, breaking/building in a new chunk, then moving back to the first chunk.

**Comment by axemwa** [comment]
ah that makes much sense thankyou ill let u know how I go

**Comment by axemwa** [comment]
I did what u said to try about moving in and out of the chunk and it worked the op was allowed to build and destroy after that

**Comment by axemwa** [comment]
ah makes sense thankyou :)

**Comment by axemwa** [comment]
Is there a command that refreshes/updates a towns cache? If not could be a useful thing to add for admins.

**Comment by LlmDl** [comment]
There is no such command as of yet.

**Comment by axemwa** [comment]
And final question do you know if these commands exist yet so that admins can change town toggles 
eg: /town {town_name} toggle fire? If not another suggestion to add to future versions :)

**Comment by LlmDl** [comment]
Already an existing suggestion: https://github.com/TownyAdvanced/Towny/issues/3000

**Comment by axemwa** [comment]
Cool I wasn't sure if it was added yet or not in dev builds, thanks.
